name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Node.js modules
      run: npm install

    - name: Install VSCE
      run: npm install -g vsce

    - name: Linting
      run: npm run tslint

    - name: Compiling
      run: npm run compile

    - name: Build VSIX file
      run: vsce package

    - name: Test extension
      continue-on-error: true
      run: DISPLAY=:99 npm test
      id: test

    - name: Retry test extension attempt 1
      continue-on-error: true
      if: steps.test.outcome=='failure'
      run: DISPLAY=:99 npm test
      id: retry1

    - name: Retry test extension attempt 2
      continue-on-error: true
      if: steps.retry1.outcome=='failure'
      run: DISPLAY=:99 npm test
      id: retry2

    - name: Set test extension status
      if: ${{ steps.test.outcome=='failure' && steps.retry1.outcome=='failure' && steps.retry2.outcome=='failure' }}
      run: |
        echo "Tests failed"
        exit 1
