name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Node.js modules
      run: npm install

    - name: Install VSCE
      run: npm install -g vsce

    - name: Linting
      run: npm run tslint

    - name: Compiling
      run: npm run compile

    - name: Build VSIX file
      run: vsce package

    - name: Test extension
      continue-on-error: true
      run: npm test
      id: test

    - name: Retry test extension attempt 1
      continue-on-error: true
      if: steps.test.outcome=='failure'
      run: npm test
      id: retry1

    - name: Retry test extension attempt 2
      continue-on-error: true
      if: steps.retry1.outcome=='failure'
      run: npm test
      id: retry2

    - name: Set test extension status
      if: ${{ steps.test.outcome=='failure' && steps.retry1.outcome=='failure' && steps.retry2.outcome=='failure' }}
      run: |
        echo "Tests failed"
        exit 1
