name: Windows-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Node.js modules
      run: npm install

    - name: Install VSCE
      run: npm install -g vsce

    - name: Linting
      run: npm run tslint

    - name: Compiling
      run: npm run compile

    - name: Build VSIX file
      run: vsce package

    - name: Test extension
      run: npm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jdtls-log
        path: .vscode-test/user-data/User/workspaceStorage/*/redhat.java/jdt_ws/.metadata/.log

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: boot-ls-log
        path: test/projects/spring-petclinic/boot-ls.log
